services:
    database:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=rovinj"
volumes:
    pg-data:
